<?php
require_once __DIR__ . '/../../includes/auth.php';require_once __DIR__ . '/../../includes/functions.php';require_once __DIR__ . '/../../includes/inventory.php';requireLogin();
$db=getDB();$id=(int)(isset($_GET['id'])?$_GET['id']:0);$stmt=$db->prepare("SELECT * FROM products WHERE id=?");$stmt->execute([$id]);$product=$stmt->fetch();if(!$product)redirect('/xamp-cosmic/modules/inventory/index.php','Product not found','error');
$stmt=$db->prepare("SELECT sm.*,u.name user_name,i.invoice_number FROM stock_movements sm LEFT JOIN users u ON u.id=sm.created_by LEFT JOIN invoices i ON sm.reference_type='invoice' AND i.id=sm.reference_id WHERE sm.product_id=? ORDER BY sm.created_at DESC,sm.id DESC LIMIT 250");$stmt->execute([$id]);$movements=$stmt->fetchAll();
$pageTitle='Stock History';require_once __DIR__ . '/../../includes/header.php';
?>
<div class="page-header"><div><span class="eyebrow">Audit history</span><h1><?php echo e($product['name']);?></h1><p class="page-subtitle">Every stock and product change, newest first.</p></div><div class="header-actions"><a class="btn btn-success btn-lg" href="/xamp-cosmic/modules/inventory/stock.php?id=<?php echo $id;?>">+ Add stock</a><?php if(isAdmin()):?><a class="btn btn-secondary" href="/xamp-cosmic/modules/products/edit.php?id=<?php echo $id;?>">Edit product</a><?php endif;?></div></div>
<div class="product-summary card"><div class="product-image large"><?php if($product['image_path']):?><img src="/xamp-cosmic<?php echo e($product['image_path']);?>" alt=""><?php else:?><span><?php echo e(strtoupper(substr($product['name'],0,1)));?></span><?php endif;?></div><div><span class="stock-pill <?php echo stockBadgeClass($product['stock_count'],$product['low_stock_threshold']);?>"><strong><?php echo formatStock($product['stock_count']);?></strong> <?php echo e($product['unit']);?></span><p><?php echo $product['barcode']?'Barcode: '.e($product['barcode']):'No barcode saved';?></p></div></div>
<div class="card"><div class="card-header"><h2>Stock history</h2></div><?php if(!$movements):?><div class="empty-state"><p>No history yet.</p></div><?php else:?><div class="timeline"><?php foreach($movements as $m):$positive=(float)$m['quantity_change']>0;$negative=(float)$m['quantity_change']<0;?><div class="timeline-item"><div class="movement-icon <?php echo $positive?'positive':($negative?'negative':'neutral');?>"><?php echo $positive?'+':($negative?'−':'•');?></div><div class="movement-main"><div class="movement-title"><strong><?php echo e(stockMovementLabel($m['movement_type']));?></strong><?php if((float)$m['quantity_change']!=0):?><span class="movement-amount <?php echo $positive?'positive':'negative';?>"><?php echo $positive?'+':'';?><?php echo formatStock($m['quantity_change']);?></span><?php endif;?></div><p><?php echo e($m['notes']);?><?php if($m['invoice_number']):?> · <a href="/xamp-cosmic/modules/invoices/view.php?id=<?php echo $m['reference_id'];?>"><?php echo e($m['invoice_number']);?></a><?php endif;?></p><small><?php echo date('d M Y, h:i A',strtotime($m['created_at']));?> · <?php echo e($m['user_name']?:'System');?></small></div><div class="movement-balance"><span><?php echo formatStock($m['stock_before']);?></span><b>→</b><strong><?php echo formatStock($m['stock_after']);?></strong></div></div><?php endforeach;?></div><?php endif;?></div>
<?php require_once __DIR__ . '/../../includes/footer.php';?>
