<?php
$pageTitle='Inventory'; require_once __DIR__ . '/../../includes/header.php'; require_once __DIR__ . '/../../includes/inventory.php';
$db=getDB(); $search=trim(isset($_GET['search'])?$_GET['search']:''); $filter=isset($_GET['filter'])?$_GET['filter']:'all';
$stats=$db->query("SELECT COUNT(*) total_products,COALESCE(SUM(stock_count),0) total_units,SUM(stock_count<=low_stock_threshold AND stock_count>0) low_count,SUM(stock_count<=0) out_count FROM products WHERE active=1")->fetch();
$sql="SELECT * FROM products WHERE active=1";$params=[];
if($search!==''){$sql.=" AND (name LIKE ? OR hsn_code LIKE ? OR barcode=?)";$params[]="%$search%";$params[]="%$search%";$params[]=$search;}
if($filter==='low')$sql.=" AND stock_count>0 AND stock_count<=low_stock_threshold"; elseif($filter==='out')$sql.=" AND stock_count<=0";
$sql.=" ORDER BY CASE WHEN stock_count<=0 THEN 0 WHEN stock_count<=low_stock_threshold THEN 1 ELSE 2 END,name";$stmt=$db->prepare($sql);$stmt->execute($params);$products=$stmt->fetchAll();
?>
<div class="page-header inventory-heading"><div><span class="eyebrow">Version 2</span><h1>Inventory</h1><p class="page-subtitle">Check stock, add deliveries and see every change.</p></div><div class="header-actions"><a class="btn btn-success btn-lg" href="/xamp-cosmic/modules/inventory/quick-add.php">+ Add stock</a><a class="btn btn-primary btn-lg" href="/xamp-cosmic/modules/products/create.php">+ New product</a><?php if(isAdmin()):?><a class="btn btn-quiet" href="/xamp-cosmic/migrations/002_inventory_v2.sql" download>Download DB upgrade</a><?php endif;?></div></div>
<div class="stats-grid compact-stats"><a class="stat-card blue" href="?filter=all"><h3>Products</h3><div class="value"><?php echo (int)$stats['total_products'];?></div></a><div class="stat-card green"><h3>Units in stock</h3><div class="value"><?php echo formatStock($stats['total_units']);?></div></div><a class="stat-card orange" href="?filter=low"><h3>Low stock</h3><div class="value"><?php echo (int)$stats['low_count'];?></div></a><a class="stat-card red" href="?filter=out"><h3>Out of stock</h3><div class="value"><?php echo (int)$stats['out_count'];?></div></a></div>
<div class="card inventory-toolbar"><form method="GET" class="search-bar"><div class="input-action inventory-search"><input id="inventorySearch" name="search" class="form-control form-control-lg" value="<?php echo e($search);?>" placeholder="Search name, HSN or barcode" autocomplete="off"><button type="button" class="btn btn-scan" data-barcode-target="inventorySearch" data-submit-after-scan="true">Scan</button></div><button class="btn btn-primary">Search</button><?php if($search||$filter!=='all'):?><a class="btn btn-secondary" href="/xamp-cosmic/modules/inventory/index.php">Clear</a><?php endif;?></form><div class="filter-pills"><a class="<?php echo $filter==='all'?'active':'';?>" href="?filter=all">All</a><a class="<?php echo $filter==='low'?'active':'';?>" href="?filter=low">Low</a><a class="<?php echo $filter==='out'?'active':'';?>" href="?filter=out">Out</a></div></div>
<?php if(!$products):?><div class="card empty-state"><h3>No products found</h3><p>Try another search or add a new product.</p></div><?php else:?><div class="product-grid"><?php foreach($products as $p):$badge=stockBadgeClass($p['stock_count'],$p['low_stock_threshold']);?><article class="product-card"><div class="product-image"><?php if($p['image_path']):?><img src="/xamp-cosmic<?php echo e($p['image_path']);?>" alt=""><?php else:?><span><?php echo e(strtoupper(substr($p['name'],0,1)));?></span><?php endif;?></div><div class="product-card-body"><div class="product-card-top"><div><h2><?php echo e($p['name']);?></h2><p><?php echo $p['barcode']?'Barcode: '.e($p['barcode']):($p['hsn_code']?'HSN: '.e($p['hsn_code']):'No barcode');?></p></div><span class="stock-pill <?php echo $badge;?>"><strong><?php echo formatStock($p['stock_count']);?></strong> <?php echo e($p['unit']);?></span></div><div class="product-card-actions"><a class="btn btn-success" href="/xamp-cosmic/modules/inventory/stock.php?id=<?php echo $p['id'];?>">+ Add stock</a><a class="btn btn-secondary" href="/xamp-cosmic/modules/inventory/history.php?id=<?php echo $p['id'];?>">History</a><?php if(isAdmin()):?><a class="btn btn-quiet" href="/xamp-cosmic/modules/products/edit.php?id=<?php echo $p['id'];?>">Edit</a><?php endif;?></div></div></article><?php endforeach;?></div><?php endif;?>
<?php require_once __DIR__ . '/../../includes/footer.php';?>
